/**
 * Enhanced SEO Auto-Generation System
 * Generates SEO fields based on actress data, timeline, and gallery information
 * NO birthdate, birthplace, or biography fields used
 */

export interface SEOData {
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string;
  h1Title: string;
  introText: string;
  ogTitle: string;
  ogDescription: string;
  ogImageUrl: string;
  canonicalUrl: string;
  seoStatus: 'red' | 'yellow' | 'green';
  autoGenerated: boolean;
  lastAutoGenerate?: string;
}

export interface ActressDataForSEO {
  id: number;
  name: string;
  firstName?: string;
  lastName?: string;
  era?: string | number;
  slug: string;
  galleryCount?: number;
  timelineEvents?: Array<{ date?: string; event?: string }>;
  existingTitle?: string;
  existingDescription?: string;
  headshotUrl?: string;
  firstGalleryImageUrl?: string;
}

/**
 * Get era text from era number
 */
function getEraText(era: string | number | undefined): string {
  const eraMap: Record<string, string> = {
    '1': '1920s-1930s',
    '2': '1940s',
    '3': '1950s',
    '4': '1960s',
    '20-30s': '1920s-1930s',
    '40s': '1940s',
    '50s': '1950s',
    '60s': '1960s',
  };
  return eraMap[String(era)] || 'Golden Age of Hollywood';
}

/**
 * Extract key information from timeline events
 */
function extractTimelineInfo(timelineEvents: Array<{ date?: string; event?: string }> = []): {
  movieTitles: string[];
  careerHighlights: string[];
  years: string[];
} {
  const movieTitles: string[] = [];
  const careerHighlights: string[] = [];
  const years: string[] = [];

  timelineEvents.forEach(event => {
    const eventText = (event.event || '').trim();
    const dateText = (event.date || '').trim();

    // Extract year from date
    if (dateText) {
      const yearMatch = dateText.match(/\b(19\d{2}|20\d{2})\b/);
      if (yearMatch) {
        years.push(yearMatch[1]);
      }
    }

    // Extract movie titles (quoted, parenthetical, or capitalized phrases)
    const moviePatterns = [
      /"([^"]{3,50})"/g, // Quoted titles
      /'([^']{3,50})'/g, // Single-quoted titles
      /\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,4})\s*\((\d{4})\)/g, // Title (Year)
    ];

    moviePatterns.forEach(pattern => {
      const matches = eventText.matchAll(pattern);
      for (const match of matches) {
        const title = match[1]?.trim();
        if (title && title.length > 3 && title.length < 50) {
          movieTitles.push(title);
        }
      }
    });

    // Extract career highlights (non-empty events)
    if (eventText && eventText.length > 10 && eventText.length < 200) {
      careerHighlights.push(eventText);
    }
  });

  return {
    movieTitles: [...new Set(movieTitles)].slice(0, 5), // Unique, max 5
    careerHighlights: careerHighlights.slice(0, 3), // Max 3 highlights
    years: [...new Set(years)].sort().slice(0, 5), // Unique years, max 5
  };
}

/**
 * Generate SEO Title (max 60 chars)
 */
function generateSEOTitle(data: ActressDataForSEO): string {
  const name = data.name;
  const era = getEraText(data.era);
  
  // Try patterns in order of preference (most descriptive first)
  const patterns = [
    `${name} - ${name} Pictures | ${era}`,
    `${name} Photos & Biography | ${era}`,
    `${name} - ${name} Gallery | ${era}`,
    `${name} Pictures - ${era} Actress`,
    `${name} - ${name} Biography`,
  ];

  // Find first pattern that fits within 60 chars
  for (const pattern of patterns) {
    if (pattern.length <= 60) {
      return pattern;
    }
  }

  // Fallback: truncate the first pattern intelligently
  const base = `${name} - ${name} Pictures | ${era}`;
  if (base.length > 60) {
    // Try shorter era text
    const shortEra = era.replace('1920s-1930s', '30s').replace('Golden Age of Hollywood', 'Hollywood');
    const shorter = `${name} - ${name} Pictures | ${shortEra}`;
    if (shorter.length <= 60) {
      return shorter;
    }
    // Last resort: truncate name if needed
    const maxNameLen = 60 - ` -  Pictures | ${shortEra}`.length;
    if (maxNameLen > 10) {
      return `${name.substring(0, maxNameLen)} - ${name.substring(0, maxNameLen)} Pictures | ${shortEra}`;
    }
  }

  return base.substring(0, 60);
}

/**
 * Generate SEO Description (150-160 chars)
 */
function generateSEODescription(data: ActressDataForSEO): string {
  const name = data.name;
  const era = getEraText(data.era);
  const galleryCount = data.galleryCount || 0;
  const timelineInfo = extractTimelineInfo(data.timelineEvents);
  const movies = timelineInfo.movieTitles;

  // Build description in parts
  let description = `${name} Pictures - Explore ${name}'s photo gallery from the ${era}. `;
  
  // Add gallery count if available
  if (galleryCount > 0) {
    description += `Browse ${galleryCount}+ ${name} photos, `;
  }
  
  // Add movie reference if available
  if (movies.length > 0) {
    description += `featuring ${name} in ${movies[0]}. `;
  } else if (timelineInfo.careerHighlights.length > 0) {
    // Use first career highlight if no movies
    const highlight = timelineInfo.careerHighlights[0];
    if (highlight.length < 50) {
      description += `${highlight}. `;
    }
  }
  
  // Closing statement
  description += `${name} biography, timeline, and rare ${name} pictures from Hollywood's Golden Age.`;

  // Ensure it's between 150-160 chars
  if (description.length < 150) {
    // Add more context
    if (movies.length > 1) {
      description = description.replace('from Hollywood\'s Golden Age.', `including ${movies[1]}. Discover ${name}'s legacy from Hollywood's Golden Age.`);
    } else {
      description += ` Discover ${name}'s contributions to classic cinema.`;
    }
  }
  
  // Trim to exactly 160 if over
  if (description.length > 160) {
    // Try to trim intelligently
    const sentences = description.split(/[.!?]\s+/);
    let trimmed = '';
    for (const sentence of sentences) {
      const test = trimmed ? `${trimmed}${sentence}. ` : `${sentence}. `;
      if (test.length <= 160) {
        trimmed = test;
      } else {
        break;
      }
    }
    if (trimmed.length >= 150) {
      description = trimmed.trim();
    } else {
      // Last resort: truncate at word boundary
      description = description.substring(0, 157).trim();
      const lastSpace = description.lastIndexOf(' ');
      if (lastSpace > 140) {
        description = description.substring(0, lastSpace) + '...';
      } else {
        description = description.substring(0, 157) + '...';
      }
    }
  }

  // Final check: ensure minimum 150
  if (description.length < 150) {
    description += ` Explore ${name}'s timeless beauty and talent.`;
    if (description.length > 160) {
      description = description.substring(0, 157) + '...';
    }
  }

  return description.substring(0, 160);
}

/**
 * Generate Keywords (5-12 keywords, comma-separated)
 */
function generateKeywords(data: ActressDataForSEO): string {
  const name = data.name;
  const era = getEraText(data.era);
  const timelineInfo = extractTimelineInfo(data.timelineEvents);
  const movies = timelineInfo.movieTitles;

  // Core keywords (always included)
  const keywords = [
    name,
    `${name} pictures`,
    `${name} photos`,
    `${name} gallery`,
    `${name} biography`,
  ];

  // Era-based keywords
  if (era.includes('1920s') || era.includes('1930s')) {
    keywords.push('1920s actresses', '1930s actresses');
  } else if (era.includes('1940s')) {
    keywords.push('1940s actresses', 'forties actresses');
  } else if (era.includes('1950s')) {
    keywords.push('1950s actresses', 'fifties actresses');
  } else if (era.includes('1960s')) {
    keywords.push('1960s actresses', 'sixties actresses');
  }

  // Add movie-related keywords (max 2)
  movies.slice(0, 2).forEach(movie => {
    keywords.push(`${name} ${movie}`);
  });

  // Add general keywords to reach 5-12 range
  const generalKeywords = [
    'glamour girls',
    'Hollywood actresses',
    'classic cinema',
    'Golden Age Hollywood',
    'vintage actresses',
  ];

  // Combine and limit to 12
  const allKeywords = [...keywords, ...generalKeywords];
  return allKeywords.slice(0, 12).join(', ');
}

/**
 * Generate H1 Title (simple, clean)
 */
function generateH1Title(data: ActressDataForSEO): string {
  return data.name;
}

/**
 * Generate Intro Text (100-220 words using timeline events)
 */
function generateIntroText(data: ActressDataForSEO): string {
  const name = data.name;
  const era = getEraText(data.era);
  const galleryCount = data.galleryCount || 0;
  const timelineInfo = extractTimelineInfo(data.timelineEvents);
  const movies = timelineInfo.movieTitles;
  const highlights = timelineInfo.careerHighlights;
  const years = timelineInfo.years;

  // Start with era and name
  let intro = `${name} was a glamorous actress from the ${era} of Hollywood. `;

  // Add movie information if available
  if (movies.length > 0) {
    if (movies.length === 1) {
      intro += `${name} appeared in the film ${movies[0]}. `;
    } else if (movies.length === 2) {
      intro += `${name} appeared in films including ${movies[0]} and ${movies[1]}. `;
    } else {
      intro += `${name} appeared in notable films such as ${movies[0]}, ${movies[1]}, and ${movies[2]}. `;
    }
  }

  // Add timeline highlights if available
  if (highlights.length > 0) {
    const firstHighlight = highlights[0];
    // Use first highlight if it's not too long
    if (firstHighlight.length < 100) {
      intro += `${firstHighlight}. `;
    } else {
      // Truncate highlight if too long
      const truncated = firstHighlight.substring(0, 97) + '...';
      intro += `${truncated}. `;
    }
  }

  // Add gallery information
  if (galleryCount > 0) {
    intro += `This comprehensive collection features ${galleryCount}+ ${name} photos, showcasing ${name}'s beauty and talent throughout her career. `;
  } else {
    intro += `This collection features ${name} photos, showcasing ${name}'s timeless beauty and elegance. `;
  }

  // Add year context if available
  if (years.length > 0) {
    const yearRange = years.length > 1 
      ? `${years[0]} to ${years[years.length - 1]}`
      : years[0];
    intro += `From ${yearRange}, ${name} captivated audiences with her presence on the silver screen. `;
  }

  // Closing statements
  intro += `Explore ${name}'s biography, timeline, and an extensive gallery of ${name} pictures from the Golden Age of Hollywood. `;
  intro += `${name} remains one of the most iconic figures from classic cinema, with a legacy that continues to inspire fans and collectors of vintage Hollywood memorabilia.`;

  // Ensure word count is between 100-220 words
  const words = intro.split(/\s+/).filter(Boolean);
  const wordCount = words.length;

  if (wordCount < 100) {
    // Add more content
    intro += ` Discover rare ${name} photos, learn about ${name}'s life and career, and explore our exclusive collection of ${name} pictures. `;
    intro += `${name}'s contributions to the silver screen have left an indelible mark on Hollywood history.`;
  } else if (wordCount > 220) {
    // Trim to ~200 words intelligently
    const sentences = intro.split(/[.!?]+\s+/).filter(Boolean);
    let trimmed = '';
    let currentWordCount = 0;
    
    for (const sentence of sentences) {
      const sentenceWords = sentence.trim().split(/\s+/).length;
      if (currentWordCount + sentenceWords <= 200) {
        trimmed += sentence.trim() + '. ';
        currentWordCount += sentenceWords;
      } else {
        // Add partial sentence if we're close
        if (currentWordCount < 180) {
          const words = sentence.split(/\s+/);
          const wordsToAdd = Math.min(words.length, 200 - currentWordCount);
          if (wordsToAdd > 5) {
            trimmed += words.slice(0, wordsToAdd).join(' ') + '. ';
          }
        }
        break;
      }
    }
    
    if (trimmed.split(/\s+/).length >= 100) {
      intro = trimmed.trim();
    } else {
      // Fallback: keep first 200 words
      intro = words.slice(0, 200).join(' ') + '.';
    }
  }

  // Final validation
  const finalWordCount = intro.split(/\s+/).filter(Boolean).length;
  if (finalWordCount < 100) {
    intro += ` ${name} represents the elegance and glamour of Hollywood's most celebrated era.`;
  }

  return intro;
}

/**
 * Calculate SEO Status (red/yellow/green)
 * Note: hasH1 can be true if h1Title exists OR if actress name exists (frontend fallback)
 */
export function calculateSEOStatus(seo: Partial<SEOData>, actressName?: string): 'red' | 'yellow' | 'green' {
  const titleLength = (seo.seoTitle || '').length;
  const descLength = (seo.seoDescription || '').length;
  const introWords = (seo.introText || '').split(/\s+/).filter(Boolean).length;
  // H1 is available if explicitly set OR if actress name exists (frontend will use it)
  const hasH1 = !!(seo.h1Title && seo.h1Title.trim()) || !!(actressName && actressName.trim());
  const hasOgImage = !!(seo.ogImageUrl && seo.ogImageUrl.trim());
  const hasCanonical = !!(seo.canonicalUrl && seo.canonicalUrl.trim());

  // RED conditions
  if (
    titleLength < 30 ||
    descLength < 120 ||
    introWords < 100 ||
    !hasH1 ||
    !hasOgImage
  ) {
    return 'red';
  }

  // YELLOW conditions
  if (
    titleLength < 50 ||
    descLength < 150 ||
    introWords < 160
  ) {
    return 'yellow';
  }

  // GREEN conditions
  if (
    titleLength >= 50 && titleLength <= 60 &&
    descLength >= 150 && descLength <= 160 &&
    introWords >= 180 && introWords <= 220 &&
    hasH1 &&
    hasOgImage &&
    hasCanonical
  ) {
    return 'green';
  }

  // Default to yellow if all required fields present but not optimal
  return 'yellow';
}

/**
 * Generate all SEO fields
 */
export function generateSEOEnhanced(
  data: ActressDataForSEO,
  baseUrl: string = 'https://www.glamourgirlsofthesilverscreen.com'
): SEOData {
  const canonicalUrl = `${baseUrl}/actress/${data.id}/${data.slug}`;
  
  // Determine OG image URL (prefer headshot, fallback to first gallery image, then default)
  let ogImageUrl = '';
  if (data.headshotUrl) {
    ogImageUrl = data.headshotUrl.startsWith('http') 
      ? data.headshotUrl 
      : `${baseUrl}${data.headshotUrl}`;
  } else if (data.firstGalleryImageUrl) {
    ogImageUrl = data.firstGalleryImageUrl.startsWith('http')
      ? data.firstGalleryImageUrl
      : `${baseUrl}${data.firstGalleryImageUrl}`;
  } else {
    ogImageUrl = `${baseUrl}/api/actresses/${data.id}/headshot`;
  }

  // Generate all fields
  const seoData: Partial<SEOData> = {
    seoTitle: generateSEOTitle(data),
    seoDescription: generateSEODescription(data),
    seoKeywords: generateKeywords(data),
    h1Title: generateH1Title(data),
    introText: generateIntroText(data),
    ogTitle: `${data.name} - Glamour Girls of the Silver Screen`,
    ogDescription: `Explore ${data.name} photos, biography, and gallery. ${data.name} Pictures from the Golden Age of Hollywood.`,
    ogImageUrl,
    canonicalUrl,
    autoGenerated: true,
    lastAutoGenerate: new Date().toISOString(),
  };

  // Calculate status
  const seoStatus = calculateSEOStatus(seoData);

  return {
    ...seoData as SEOData,
    seoStatus,
  };
}
