// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig, env } from "prisma/config";

// Prisma CLI doesn't automatically load Next.js-style `.env.local`.
// Load `.env` first, then override with `.env.local`.
dotenv.config({ path: ".env" });
dotenv.config({ path: ".env.local", override: true });

// For prisma generate, DATABASE_URL is not required (only needed for migrations)
// Use a dummy URL if not available to prevent build errors
const databaseUrl = process.env.DATABASE_URL || "postgresql://user:password@localhost:5432/db";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
