import { NextRequest, NextResponse } from 'next/server';
import pool from '@/lib/db';
import { generateSEOEnhanced, calculateSEOStatus } from '@/lib/seo/generate-seo-enhanced';
import { requireAdminApi } from '@/app/api/admin/_auth';

// GET - Get SEO data for an actress
export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { error } = await requireAdminApi(request);
  if (error) return error;
  try {
    const { id } = await params;
    const actressId = parseInt(id);

    if (isNaN(actressId)) {
      return NextResponse.json({ error: 'Invalid ID' }, { status: 400 });
    }

    // Fetch actress data
    const [actressRows] = await pool.execute(
      `SELECT 
        id, nm, firstname, familiq, middlenames, godini, theirman, slug,
        seo_title, meta_description, meta_keywords, h1_title, intro_text,
        og_title, og_description, og_image, canonical_url,
        seo_status, auto_generated, last_auto_generate
       FROM girls WHERE id = ?`,
      [actressId]
    ) as any[];

    if (!actressRows || actressRows.length === 0) {
      return NextResponse.json(
        { error: 'Actress not found' },
        { status: 404 }
      );
    }

    const row = actressRows[0];

    // Fetch timeline events
    const [timelineRows] = await pool.execute(
      `SELECT shrttext as date, lngtext as event 
       FROM girlinfos 
       WHERE girlid = ? 
       ORDER BY ord ASC`,
      [actressId]
    ) as any[];

    // Count gallery images
    const [galleryCountRows] = await pool.execute(
      `SELECT COUNT(*) as count FROM images WHERE girlid = ? AND mytp = 4`,
      [actressId]
    ) as any[];
    const galleryCount = galleryCountRows[0]?.count || 0;

    // Get headshot URL
    const headshotUrl = `/api/actresses/${actressId}/headshot`;

    // Get first gallery image
    const [firstGalleryRows] = await pool.execute(
      `SELECT path FROM images WHERE girlid = ? AND mytp = 4 ORDER BY id ASC LIMIT 1`,
      [actressId]
    ) as any[];
    const firstGalleryImageUrl = firstGalleryRows[0]?.path || null;

    const seoData = {
      seoTitle: row.seo_title || '',
      seoDescription: row.meta_description || '',
      seoKeywords: row.meta_keywords || '',
      h1Title: row.h1_title || '',
      introText: row.intro_text || '',
      ogTitle: row.og_title || '',
      ogDescription: row.og_description || '',
      ogImageUrl: row.og_image || '',
      canonicalUrl: row.canonical_url || '',
      seoStatus: row.seo_status || 'red',
      autoGenerated: Boolean(row.auto_generated),
      lastAutoGenerate: row.last_auto_generate || null,
    };

    // Calculate current status if not set
    if (!row.seo_status) {
      const calculatedStatus = calculateSEOStatus(seoData);
      seoData.seoStatus = calculatedStatus;
    }

    return NextResponse.json({
      ...seoData,
      metadata: {
        actressName: row.nm,
        galleryCount,
        timelineEventCount: timelineRows.length,
      },
    });
  } catch (error) {
    console.error('Error fetching SEO data:', error);
    return NextResponse.json(
      { error: 'Failed to fetch SEO data' },
      { status: 500 }
    );
  }
}

// POST - Save SEO data
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { error } = await requireAdminApi(request);
  if (error) return error;
  try {
    const { id } = await params;
    const actressId = parseInt(id);
    const data = await request.json();

    if (isNaN(actressId)) {
      return NextResponse.json({ error: 'Invalid ID' }, { status: 400 });
    }

    // Calculate SEO status
    const seoStatus = calculateSEOStatus(data);

    // Update SEO data
    await pool.execute(
      `UPDATE girls SET
        seo_title = ?,
        meta_description = ?,
        meta_keywords = ?,
        h1_title = ?,
        intro_text = ?,
        og_title = ?,
        og_description = ?,
        og_image = ?,
        canonical_url = ?,
        seo_status = ?,
        auto_generated = ?,
        last_auto_generate = ?
       WHERE id = ?`,
      [
        data.seoTitle || null,
        data.seoDescription || null,
        data.seoKeywords || null,
        data.h1Title || null,
        data.introText || null,
        data.ogTitle || null,
        data.ogDescription || null,
        data.ogImageUrl || null,
        data.canonicalUrl || null,
        seoStatus,
        data.autoGenerated || false,
        data.lastAutoGenerate || null,
        actressId,
      ]
    );

    return NextResponse.json({
      success: true,
      seoStatus,
      message: 'SEO data saved successfully',
    });
  } catch (error) {
    console.error('Error saving SEO data:', error);
    return NextResponse.json(
      { error: 'Failed to save SEO data' },
      { status: 500 }
    );
  }
}

