'use client';

import { useState, useEffect, useCallback } from 'react';
import { Button, App } from 'antd';
import { calculateSEOStatus, type SEOData } from '@/lib/seo/generate-seo-enhanced';

const { useApp } = App;

interface SEOFormSectionProps {
  actressId: number;
  actressData: {
    name: string;
    firstName?: string;
    lastName?: string;
    era?: string | number;
    slug: string;
    galleryCount?: number;
  };
  initialSEO?: Partial<SEOData>;
  onChange?: (seo: SEOData) => void;
}

// Helper to check if H1 is available (either from SEO or fallback to name)
function hasH1Available(h1Title: string | undefined | null, actressName: string): boolean {
  return !!(h1Title?.trim() || actressName?.trim());
}

export default function SEOFormSectionEnhanced({ 
  actressId,
  actressData, 
  initialSEO, 
  onChange
}: SEOFormSectionProps) {
  const { message } = useApp();
  const [seo, setSeo] = useState<SEOData>(() => {
    if (initialSEO) {
      return {
        seoTitle: initialSEO.seoTitle || '',
        seoDescription: initialSEO.seoDescription || '',
        seoKeywords: initialSEO.seoKeywords || '',
        h1Title: initialSEO.h1Title || '',
        introText: initialSEO.introText || '',
        ogTitle: initialSEO.ogTitle || '',
        ogDescription: initialSEO.ogDescription || '',
        ogImageUrl: initialSEO.ogImageUrl || '',
        canonicalUrl: initialSEO.canonicalUrl || '',
        seoStatus: initialSEO.seoStatus || 'red',
        autoGenerated: initialSEO.autoGenerated || false,
        lastAutoGenerate: initialSEO.lastAutoGenerate,
      };
    }
    return {
      seoTitle: '',
      seoDescription: '',
      seoKeywords: '',
      h1Title: '',
      introText: '',
      ogTitle: '',
      ogDescription: '',
      ogImageUrl: '',
      canonicalUrl: '',
      seoStatus: 'red' as const,
      autoGenerated: false,
    };
  });

  const [seoStatus, setSeoStatus] = useState<'red' | 'yellow' | 'green'>('red');
  const [isLoading, setIsLoading] = useState(false);
  const [isAutoGenerating, setIsAutoGenerating] = useState(false);

  // Calculate status whenever SEO data changes
  useEffect(() => {
    const status = calculateSEOStatus(seo, actressData.name);
    setSeoStatus(status);
    if (onChange) {
      onChange({ ...seo, seoStatus: status });
    }
  }, [seo, actressData.name, onChange]);

  // Load SEO data on mount
  useEffect(() => {
    loadSEOData();
  }, [actressId]);

  const loadSEOData = async () => {
    try {
      setIsLoading(true);
      const response = await fetch(`/api/admin/girls/${actressId}/seo`);
      if (response.ok) {
        const data = await response.json();
        setSeo({
          seoTitle: data.seoTitle || '',
          seoDescription: data.seoDescription || '',
          seoKeywords: data.seoKeywords || '',
          h1Title: data.h1Title || '',
          introText: data.introText || '',
          ogTitle: data.ogTitle || '',
          ogDescription: data.ogDescription || '',
          ogImageUrl: data.ogImageUrl || '',
          canonicalUrl: data.canonicalUrl || '',
          seoStatus: data.seoStatus || 'red',
          autoGenerated: data.autoGenerated || false,
          lastAutoGenerate: data.lastAutoGenerate,
        });
      }
    } catch (error) {
      console.error('Error loading SEO data:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleAutoGenerate = async () => {
    try {
      setIsAutoGenerating(true);
      const response = await fetch(`/api/admin/girls/${actressId}/seo/auto-generate`, {
        method: 'POST',
      });
      
      if (response.ok) {
        const data = await response.json();
        console.log('Auto-generate response:', data);
        // Set the SEO data from the response - the endpoint already saved it to DB
        if (data.seoData) {
          const newSeo = {
            seoTitle: data.seoData.seoTitle || '',
            seoDescription: data.seoData.seoDescription || '',
            seoKeywords: data.seoData.seoKeywords || '',
            h1Title: data.seoData.h1Title || '',
            introText: data.seoData.introText || '',
            ogTitle: data.seoData.ogTitle || '',
            ogDescription: data.seoData.ogDescription || '',
            ogImageUrl: data.seoData.ogImageUrl || '',
            canonicalUrl: data.seoData.canonicalUrl || '',
            seoStatus: calculateSEOStatus(data.seoData, actressData.name),
            autoGenerated: true,
            lastAutoGenerate: new Date().toISOString(),
          };
          console.log('Setting SEO data:', newSeo);
          setSeo(newSeo);
          // Update onChange callback if provided
          if (onChange) {
            onChange(newSeo);
          }
        } else {
          console.warn('No seoData in response:', data);
        }
        message.success('SEO data auto-generated and saved successfully!');
      } else {
        const error = await response.json();
        message.error(`Error: ${error.error || 'Failed to auto-generate SEO data'}`);
      }
    } catch (error) {
      console.error('Error auto-generating SEO:', error);
      message.error('Error auto-generating SEO data');
    } finally {
      setIsAutoGenerating(false);
    }
  };

  const handleSave = async () => {
    try {
      setIsLoading(true);
      // Prepare the data to send - ensure all fields are included
      const dataToSave = {
        seoTitle: seo.seoTitle || '',
        seoDescription: seo.seoDescription || '',
        seoKeywords: seo.seoKeywords || '',
        h1Title: seo.h1Title || '',
        introText: seo.introText || '',
        ogTitle: seo.ogTitle || '',
        ogDescription: seo.ogDescription || '',
        ogImageUrl: seo.ogImageUrl || '',
        canonicalUrl: seo.canonicalUrl || '',
      };
      
      console.log('Saving SEO data:', dataToSave);
      
      const response = await fetch(`/api/admin/girls/${actressId}/seo`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(dataToSave),
      });
      
      if (response.ok) {
        const data = await response.json();
        // Update status but keep the current SEO data (don't reload from DB)
        setSeoStatus(data.seoStatus);
        message.success('SEO data saved successfully!');
        // Don't reload - keep the current form state since we just saved it
      } else {
        const error = await response.json();
        message.error(`Error: ${error.error || 'Failed to save SEO data'}`);
      }
    } catch (error) {
      console.error('Error saving SEO:', error);
      message.error('Error saving SEO data');
    } finally {
      setIsLoading(false);
    }
  };

  const handleChange = (field: keyof SEOData, value: string | boolean) => {
    setSeo(prev => ({ ...prev, [field]: value }));
  };

  const getStatusColor = (status: 'red' | 'yellow' | 'green') => {
    switch (status) {
      case 'green': return 'bg-green-100 text-green-800 border-green-300';
      case 'yellow': return 'bg-yellow-100 text-yellow-800 border-yellow-300';
      case 'red': return 'bg-red-100 text-red-800 border-red-300';
    }
  };

  const titleLength = seo.seoTitle.length;
  const descLength = seo.seoDescription.length;
  const introWords = seo.introText.split(/\s+/).filter(Boolean).length;

  return (
    <div className="space-y-6">
      {/* SEO Status Indicator */}
      <div className={`p-4 rounded-lg border-2 ${getStatusColor(seoStatus)}`}>
        <div className="flex items-center justify-between mb-2">
          <h3 className="font-protest font-semibold" style={{ fontSize: '14px' }}>
            SEO Status: {seoStatus.toUpperCase()}
          </h3>
          <div className="flex gap-2">
            <Button
              onClick={handleAutoGenerate}
              loading={isAutoGenerating}
              size="small"
            >
              Auto-Generate
            </Button>
            <Button
              onClick={handleSave}
              loading={isLoading}
              size="small"
              style={{
                fontWeight: 'bold',
                borderWidth: '2px',
                borderStyle: 'solid',
                borderColor: '#000000',
                backgroundColor: '#f5f5f5',
                color: '#000000'
              }}
            >
              Save SEO
            </Button>
          </div>
        </div>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs">
          <div className={titleLength >= 50 && titleLength <= 60 ? 'text-green-700' : titleLength >= 30 ? 'text-yellow-700' : 'text-red-700'}>
            Title: {titleLength}/60 {titleLength >= 50 && titleLength <= 60 ? '✓' : titleLength < 30 ? '✗' : '⚠'}
          </div>
          <div className={descLength >= 150 && descLength <= 160 ? 'text-green-700' : descLength >= 120 ? 'text-yellow-700' : 'text-red-700'}>
            Desc: {descLength}/160 {descLength >= 150 && descLength <= 160 ? '✓' : descLength < 120 ? '✗' : '⚠'}
          </div>
          <div className={seo.h1Title ? 'text-green-700' : (actressData.name ? 'text-yellow-700' : 'text-red-700')}>
            H1: {seo.h1Title ? '✓' : (actressData.name ? '⚠ (using name)' : '✗')}
          </div>
          <div className={introWords >= 180 && introWords <= 220 ? 'text-green-700' : introWords >= 100 ? 'text-yellow-700' : 'text-red-700'}>
            Intro: {introWords} words {introWords >= 180 && introWords <= 220 ? '✓' : introWords < 100 ? '✗' : '⚠'}
          </div>
          <div className={seo.ogImageUrl ? 'text-green-700' : 'text-red-700'}>
            OG Image: {seo.ogImageUrl ? '✓' : '✗'}
          </div>
          <div className={seo.canonicalUrl ? 'text-green-700' : 'text-yellow-700'}>
            Canonical: {seo.canonicalUrl ? '✓' : '⚠'}
          </div>
        </div>
        {seo.autoGenerated && seo.lastAutoGenerate && (
          <div className="mt-2 text-xs text-gray-600">
            Auto-generated: {new Date(seo.lastAutoGenerate).toLocaleString()}
          </div>
        )}
      </div>

      {/* SEO Title */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          SEO Title (30-60 chars) *
        </label>
        <input
          type="text"
          value={seo.seoTitle}
          onChange={(e) => handleChange('seoTitle', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          maxLength={60}
          placeholder="e.g., Julie Adams - Julie Adams Pictures | 50s Actress"
        />
        <p className="text-xs text-gray-500 mt-0.5">
          {titleLength < 30 ? 'Too short (min 30)' : titleLength > 60 ? 'Too long (max 60)' : titleLength >= 50 ? 'Optimal (50-60)' : 'Good (30-49)'}
        </p>
      </div>

      {/* SEO Description */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          SEO Description (120-160 chars) *
        </label>
        <textarea
          value={seo.seoDescription}
          onChange={(e) => handleChange('seoDescription', e.target.value)}
          rows={3}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          maxLength={160}
          placeholder="e.g., Julie Adams Pictures - Explore Julie Adams' photo gallery from the 50s era..."
        />
        <p className="text-xs text-gray-500 mt-0.5">
          {descLength < 120 ? 'Too short (min 120)' : descLength > 160 ? 'Too long (max 160)' : descLength >= 150 ? 'Optimal (150-160)' : 'Good (120-149)'}
        </p>
      </div>

      {/* SEO Keywords */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          SEO Keywords (comma-separated, 5-12 keywords)
        </label>
        <input
          type="text"
          value={seo.seoKeywords}
          onChange={(e) => handleChange('seoKeywords', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="e.g., Julie Adams, Julie Adams pictures, 50s actresses, Hollywood"
        />
      </div>

      {/* H1 Title */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          H1 / Page Headline * {seo.h1Title ? '✓' : (actressData.name ? <span className="text-yellow-600">⚠ (will use: {actressData.name})</span> : <span className="text-red-600">✗ Missing</span>)}
        </label>
        <input
          type="text"
          value={seo.h1Title}
          onChange={(e) => handleChange('h1Title', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="e.g., Julie Adams"
        />
      </div>

      {/* Intro Text */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          Intro Text (100-220 words) * {introWords >= 180 && introWords <= 220 ? '✓' : introWords >= 100 ? '⚠' : <span className="text-red-600">✗ Too short</span>}
        </label>
        <textarea
          value={seo.introText}
          onChange={(e) => handleChange('introText', e.target.value)}
          rows={8}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="Write an engaging introduction (100-220 words)..."
        />
        <p className="text-xs text-gray-500 mt-0.5">
          Word count: {introWords} {introWords < 100 ? '(min 100)' : introWords > 220 ? '(max 220)' : introWords >= 180 ? '(optimal 180-220)' : '(good 100-179)'}
        </p>
      </div>

      {/* OG Title */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">OG Title</label>
        <input
          type="text"
          value={seo.ogTitle}
          onChange={(e) => handleChange('ogTitle', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="e.g., Julie Adams - Glamour Girls of the Silver Screen"
        />
      </div>

      {/* OG Description */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">OG Description</label>
        <textarea
          value={seo.ogDescription}
          onChange={(e) => handleChange('ogDescription', e.target.value)}
          rows={2}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="e.g., Explore Julie Adams photos, biography, and gallery..."
        />
      </div>

      {/* OG Image URL */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">
          OG Image URL {seo.ogImageUrl ? '✓' : <span className="text-red-600">✗ Missing</span>}
        </label>
        <input
          type="text"
          value={seo.ogImageUrl}
          onChange={(e) => handleChange('ogImageUrl', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="https://example.com/image.jpg"
        />
      </div>

      {/* Canonical URL */}
      <div>
        <label className="block text-xs font-medium text-gray-700 mb-1">Canonical URL</label>
        <input
          type="text"
          value={seo.canonicalUrl}
          onChange={(e) => handleChange('canonicalUrl', e.target.value)}
          className="w-full px-3 py-1.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 text-xs"
          placeholder="https://www.glamourgirlsofthesilverscreen.com/actress/1/julie-adams"
        />
      </div>
    </div>
  );
}

